apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-storage-backend.fullname" . }}
  labels:
  {{- include "helm-storage-backend.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
    verbs:
      - "get"
      - "list"
