ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.runner.helm # Computed during fetching the manifest
  name: run
  license:
    name: "Apache 2.0"
  displayName: Run Action for Helm Runner
  description: Running Helm operations
  documentationURL: https://helm.sh/
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  appVersion: "3.x.x"

  implements:
    - path: cap.core.interface.runner.generic.run
      revision: 0.1.0
    - path: cap.interface.runner.helm.run
      revision: 0.1.0

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: 0.1.0

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: helm
        templates:
          - name: helm
            inputs:
              artifacts:
                # The input parameters that holds information what should be executed
                - name: input-parameters
                  path: "/helm-args"
                - name: runner-context
                  path: "/runner-context"
            outputs:
              artifacts:
                - name: helm-release
                  globalName: helm-release
                  path: "/helm-release.yaml"
                - name: additional
                  globalName: additional
                  path: "/additional.yaml"
            container:
              image: gcr.io/projectvoltron/pr/helm-runner:PR-102
              env:
                - name: RUNNER_CONTEXT_PATH
                  value: "{{inputs.artifacts.runner-context.path}}"
                - name: RUNNER_ARGS_PATH
                  value: "{{inputs.artifacts.input-parameters.path}}"
                - name: RUNNER_OUTPUT_HELM_RELEASE_FILE_PATH
                  value: "{{outputs.artifacts.helm-release.path}}"
                - name: RUNNER_OUTPUT_ADDITIONAL_FILE_PATH
                  value: "{{outputs.artifacts.additional.path}}"
                - name: RUNNER_LOGGER_DEV_MODE
                  value: "true"

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
