ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.runner.helm # Computed during fetching the manifest
  name: run
  license:
    name: "Apache 2.0"
  displayName: Run Action for Helm Runner
  description: Running Helm operations
  documentationURL: https://helm.sh/
  maintainers:
    - email: team@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  appVersion: "3.x.x"

  implements:
    - name: cap.core.interface.runner.generic.run
      revision: "0.1.0"
    - name: cap.interface.runner.helm.run
      revision: "0.1.0"

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: "0.1.0"

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: helm
        templates:
          - name: helm
            outputs:
              artifacts:
                - name: helm-release
                  globalName: helm-release
                  path: "/out/helm-release"
            container:
              image: gcr.io/projectvoltron/helm-runner:0.1.0
              command: [ "run.sh" ]
              args:
                - --params
                - "{{ .Input.parameters }}"
                - --output-path
                - "{{`{{outputs.artifacts.helm-release.path}}`}}"

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
