ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.runner.helm
  name: upgrade
  license:
    name: "Apache 2.0"
  displayName: "Upgrade"
  description: "Upgrade action for Helm Runner"
  documentationURL: https://helm.sh/
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  appVersion: "3.x.x"

  implements:
    - path: cap.core.interface.runner.generic.run
      revision: 0.1.0
    - path: cap.interface.runner.helm.upgrade
      revision: 0.1.0

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: 0.1.0

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0

  outputTypeInstanceRelations: {}
    # Do not upload helm-release, as it will be updated in place.
    # Do not upload `additional` TypeInstance by default.
    # Upper-level workflows may define it in the outputTypeInstanceRelations.

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: helm
        templates:
          - name: helm
            inputs:
              artifacts:
                # The input parameters that holds information what should be executed
                - name: input-parameters
                - name: helm-release
                - name: runner-context
            outputs:
              artifacts:
                - name: helm-release
                  from: "{{steps.helm-upgrade.outputs.artifacts.helm-release}}"
                - name: additional
                  from: "{{steps.helm-upgrade.outputs.artifacts.additional}}"
                  optional: true
            steps:
              - - name: helm-upgrade
                  capact-updateTypeInstances:
                    - name: helm-release
                      from: helm-release
                  template: helm-upgrade
                  arguments:
                    artifacts:
                      # The input parameters that holds information what should be executed
                      - name: input-parameters
                        from: "{{inputs.artifacts.input-parameters}}"
                      - name: helm-release
                        from: "{{inputs.artifacts.helm-release}}"
                      - name: runner-context
                        from: "{{inputs.artifacts.runner-context}}"

          - name: helm-upgrade
            inputs:
              artifacts:
                - name: input-parameters
                  path: "/runner-args"
                - name: helm-release
                  path: "/helm-release.yaml"
                - name: runner-context
                  path: "/runner-context"
            outputs:
              artifacts:
                - name: helm-release
                  path: "/helm-release.yaml"
                - name: additional
                  path: "/additional.yaml"
                  optional: true
            container:
              image: ghcr.io/capactio/pr/helm-runner:PR-310
              env:
                - name: RUNNER_CONTEXT_PATH
                  value: "{{inputs.artifacts.runner-context.path}}"
                - name: RUNNER_ARGS_PATH
                  value: "{{inputs.artifacts.input-parameters.path}}"
                - name: RUNNER_HELM_RELEASE_PATH
                  value: "{{inputs.artifacts.helm-release.path}}"
                - name: RUNNER_LOGGER_DEV_MODE
                  value: "true"
                - name: RUNNER_COMMAND
                  value: "upgrade"
                - name: RUNNER_OUTPUT_HELM_RELEASE_FILE_PATH
                  value: "{{outputs.artifacts.helm-release.path}}"
                - name: RUNNER_OUTPUT_ADDITIONAL_FILE_PATH
                  value: "{{outputs.artifacts.additional.path}}"

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
