apiVersion: v2
name: ingress-controller
description: A Helm chart for Nginx Ingress Controller for Capact installation

type: application

version: 0.6.0

dependencies:
  - name: ingress-nginx
    version: "3.35.x"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
