ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: run-input
  prefix: cap.type.runner.helm  # Computed during fetching the manifest
  displayName: Input parameters for Run action
  description: Describes input parameters for Run action of the Helm Runner.
  documentationURL: https://helm.sh/docs
  supportURL: https://helm.sh
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The input schema for Helm Runner",
        "examples": [
          {
            "context": {
              "platform": {
                "foo": "bar"
              },
              "name": "foo",
              "dryRun": false
            },
            "args": {
              "command": "install",
              "name": "foo",
              "chart": {
                "name": "postgresql",
                "repo": "https://charts.bitnami.com/bitnami"
              },
              "output": {
                "directory": "./",
                "helmRelease": { "fileName": "release.yaml" }
              }
            }
          }
        ],
        "required": [
            "context",
            "args"
        ],
        "properties": {
          "context": {
            "$id": "#/properties/context",
            "type": "object",
            "title": "Runner context",
            "required": [
                "dryRun",
                "name"
            ],
            "properties": {
              "dryRun": {
                "$id": "#/properties/context/properties/dryRun",
                "type": "boolean",
                "title": "Describes if the action should test ability to execute, not actually execute",
                "default": false
              },
              "name": {
                "$id": "#/properties/context/properties/name",
                "type": "string",
                "title": "Describes the name of current run"
              },
              "platform": {
                "$id": "#/properties/context/properties/platform",
                "type": "object",
                "additionalProperties": true,
                "default": {},
                "title": "Describes platform-specific values"
              }
            },
            "additionalProperties": false
          },
          "args": {
            "$id": "#/properties/args",
            "type": "object",
            "title": "Arguments for Helm Runner",
            "additionalProperties": false,
            "required": [
                "command",
                "chart"
            ],
            "properties": {
              "command": {
                "$id": "#/properties/args/properties/command",
                "type": "string",
                "enum": [
                    "install",
                    "upgrade",
                    "delete"
                ],
                "title": "The command to run for Helm"
              },
              "name": {
                "$id": "#/properties/args/properties/name",
                "type": "string",
                "title": "The name of installed release"
              },
              "chart": {
                "$id": "#/properties/args/properties/chart",
                "type": "object",
                "title": "The chart data",
                "required": [
                    "name"
                ],
                "properties": {
                  "name": {
                    "$id": "#/properties/args/properties/chart/properties/name",
                    "type": "string",
                    "title": "The name of Chart",
                    "default": ""
                  },
                  "version": {
                    "$id": "#/properties/args/properties/chart/properties/version",
                    "type": "string",
                    "title": "Specify the exact chart version to use. If this is not specified, the latest version is used",
                    "default": ""
                  },
                  "repo": {
                    "$id": "#/properties/args/properties/repo",
                    "type": "string",
                    "title": "Chart repository URL where to locate the requested chart"
                  }
                },
                "additionalProperties": false
              },
              "noHooks": {
                "$id": "#/properties/args/properties/noHooks",
                "type": "boolean",
                "title": "Prevent hooks from running during install",
                "default": false
              },
              "generateName": {
                "$id": "#/properties/args/properties/generateName",
                "type": "boolean",
                "title": "Generate release name",
                "default": false
              },
              "replace": {
                "$id": "#/properties/args/properties/replace",
                "type": "boolean",
                "title": "Re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production",
                "default": false
              },
              "values": {
                "$id": "#/properties/args/properties/values",
                "type": "object",
                "title": "The values for chart",
                "additionalProperties": true
              },
              "valuesFromFile": {
                "$id": "#/properties/args/properties/valuesFromFile",
                "type": "string",
                "title": "The path for file with values for chart"
              },
              "output": {
                "$id": "#/properties/args/properties/output",
                "type": "object",
                "title": "The parameters for output files",
                "additionalProperties": false,
                "required": [
                    "directory",
                    "default"
                ],
                "properties": {
                  "helmRelease": {
                    "$id": "#/properties/args/properties/output/properties/helmRelease",
                    "type": "object",
                    "title": "The parameters for Helm release output file",
                    "additionalProperties": false,
                    "required": [
                        "fileName"
                    ],
                    "properties": {
                      "fileName": {
                        "$id": "#/properties/args/properties/output/properties/helmRelease/properties/fileName",
                        "type": "string",
                        "title": "The file name of the helm-release output file"
                      }
                    }
                  },
                  "additional": {
                    "$id": "#/properties/args/properties/output/properties/additional",
                    "type": "object",
                    "title": "The parameters for additional output file",
                    "additionalProperties": false,
                    "required": [
                        "value",
                        "fileName"
                    ],
                    "properties": {
                      "value": {
                        "$id": "#/properties/args/properties/output/properties/additional/properties/value",
                        "type": "object",
                        "title": "The shape for additional output file",
                        "additionalProperties": true
                      },
                      "fileName": {
                        "$id": "#/properties/args/properties/output/properties/additional/properties/fileName",
                        "type": "string",
                        "title": "The file name of the output file"
                      }
                    }
                  },
                  "directory": {
                    "$id": "#/properties/args/properties/output/properties/directory",
                    "type": "string",
                    "title": "The directory path for the output files"
                  }
                }
              }
            }
          }
        },
        "additionalProperties": false
      }

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
