// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/authentication/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Action) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionInput) DeepCopyInto(out *ActionInput) {
	*out = *in
	if in.TypeInstances != nil {
		in, out := &in.TypeInstances, &out.TypeInstances
		*out = new([]InputTypeInstance)
		if **in != nil {
			in, out := *in, *out
			*out = make([]InputTypeInstance, len(*in))
			copy(*out, *in)
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(InputParameters)
		**out = **in
	}
	if in.ActionPolicy != nil {
		in, out := &in.ActionPolicy, &out.ActionPolicy
		*out = new(ActionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionInput.
func (in *ActionInput) DeepCopy() *ActionInput {
	if in == nil {
		return nil
	}
	out := new(ActionInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionList) DeepCopyInto(out *ActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionList.
func (in *ActionList) DeepCopy() *ActionList {
	if in == nil {
		return nil
	}
	out := new(ActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionOutput) DeepCopyInto(out *ActionOutput) {
	*out = *in
	if in.TypeInstances != nil {
		in, out := &in.TypeInstances, &out.TypeInstances
		*out = new([]OutputTypeInstanceDetails)
		if **in != nil {
			in, out := *in, *out
			*out = make([]OutputTypeInstanceDetails, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionOutput.
func (in *ActionOutput) DeepCopy() *ActionOutput {
	if in == nil {
		return nil
	}
	out := new(ActionOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionPolicy) DeepCopyInto(out *ActionPolicy) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionPolicy.
func (in *ActionPolicy) DeepCopy() *ActionPolicy {
	if in == nil {
		return nil
	}
	out := new(ActionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	in.ActionRef.DeepCopyInto(&out.ActionRef)
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(ActionInput)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvancedRendering != nil {
		in, out := &in.AdvancedRendering, &out.AdvancedRendering
		*out = new(AdvancedRendering)
		(*in).DeepCopyInto(*out)
	}
	if in.RenderedActionOverride != nil {
		in, out := &in.RenderedActionOverride, &out.RenderedActionOverride
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Run != nil {
		in, out := &in.Run, &out.Run
		*out = new(bool)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.Cancel != nil {
		in, out := &in.Cancel, &out.Cancel
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionSpec.
func (in *ActionSpec) DeepCopy() *ActionSpec {
	if in == nil {
		return nil
	}
	out := new(ActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionStatus) DeepCopyInto(out *ActionStatus) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Runner != nil {
		in, out := &in.Runner, &out.Runner
		*out = new(RunnerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(ActionOutput)
		(*in).DeepCopyInto(*out)
	}
	if in.Rendering != nil {
		in, out := &in.Rendering, &out.Rendering
		*out = new(RenderingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CreatedBy != nil {
		in, out := &in.CreatedBy, &out.CreatedBy
		*out = new(v1.UserInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.RunBy != nil {
		in, out := &in.RunBy, &out.RunBy
		*out = new(v1.UserInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.CanceledBy != nil {
		in, out := &in.CanceledBy, &out.CanceledBy
		*out = new(v1.UserInfo)
		(*in).DeepCopyInto(*out)
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionStatus.
func (in *ActionStatus) DeepCopy() *ActionStatus {
	if in == nil {
		return nil
	}
	out := new(ActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedRendering) DeepCopyInto(out *AdvancedRendering) {
	*out = *in
	if in.RenderingIteration != nil {
		in, out := &in.RenderingIteration, &out.RenderingIteration
		*out = new(RenderingIteration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedRendering.
func (in *AdvancedRendering) DeepCopy() *AdvancedRendering {
	if in == nil {
		return nil
	}
	out := new(AdvancedRendering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedRenderingStatus) DeepCopyInto(out *AdvancedRenderingStatus) {
	*out = *in
	if in.RenderingIteration != nil {
		in, out := &in.RenderingIteration, &out.RenderingIteration
		*out = new(RenderingIterationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedRenderingStatus.
func (in *AdvancedRenderingStatus) DeepCopy() *AdvancedRenderingStatus {
	if in == nil {
		return nil
	}
	out := new(AdvancedRenderingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputParameters) DeepCopyInto(out *InputParameters) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputParameters.
func (in *InputParameters) DeepCopy() *InputParameters {
	if in == nil {
		return nil
	}
	out := new(InputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputTypeInstance) DeepCopyInto(out *InputTypeInstance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputTypeInstance.
func (in *InputTypeInstance) DeepCopy() *InputTypeInstance {
	if in == nil {
		return nil
	}
	out := new(InputTypeInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputTypeInstanceToProvide) DeepCopyInto(out *InputTypeInstanceToProvide) {
	*out = *in
	if in.TypeRef != nil {
		in, out := &in.TypeRef, &out.TypeRef
		*out = new(ManifestReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputTypeInstanceToProvide.
func (in *InputTypeInstanceToProvide) DeepCopy() *InputTypeInstanceToProvide {
	if in == nil {
		return nil
	}
	out := new(InputTypeInstanceToProvide)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestReference) DeepCopyInto(out *ManifestReference) {
	*out = *in
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestReference.
func (in *ManifestReference) DeepCopy() *ManifestReference {
	if in == nil {
		return nil
	}
	out := new(ManifestReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputTypeInstanceDetails) DeepCopyInto(out *OutputTypeInstanceDetails) {
	*out = *in
	if in.TypeRef != nil {
		in, out := &in.TypeRef, &out.TypeRef
		*out = new(ManifestReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputTypeInstanceDetails.
func (in *OutputTypeInstanceDetails) DeepCopy() *OutputTypeInstanceDetails {
	if in == nil {
		return nil
	}
	out := new(OutputTypeInstanceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderingIteration) DeepCopyInto(out *RenderingIteration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderingIteration.
func (in *RenderingIteration) DeepCopy() *RenderingIteration {
	if in == nil {
		return nil
	}
	out := new(RenderingIteration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderingIterationStatus) DeepCopyInto(out *RenderingIterationStatus) {
	*out = *in
	if in.InputTypeInstancesToProvide != nil {
		in, out := &in.InputTypeInstancesToProvide, &out.InputTypeInstancesToProvide
		*out = new([]InputTypeInstanceToProvide)
		if **in != nil {
			in, out := *in, *out
			*out = make([]InputTypeInstanceToProvide, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderingIterationStatus.
func (in *RenderingIterationStatus) DeepCopy() *RenderingIterationStatus {
	if in == nil {
		return nil
	}
	out := new(RenderingIterationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderingStatus) DeepCopyInto(out *RenderingStatus) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(ResolvedActionInput)
		(*in).DeepCopyInto(*out)
	}
	if in.TypeInstancesToLock != nil {
		in, out := &in.TypeInstancesToLock, &out.TypeInstancesToLock
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdvancedRendering != nil {
		in, out := &in.AdvancedRendering, &out.AdvancedRendering
		*out = new(AdvancedRenderingStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderingStatus.
func (in *RenderingStatus) DeepCopy() *RenderingStatus {
	if in == nil {
		return nil
	}
	out := new(RenderingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedActionInput) DeepCopyInto(out *ResolvedActionInput) {
	*out = *in
	if in.TypeInstances != nil {
		in, out := &in.TypeInstances, &out.TypeInstances
		*out = new([]InputTypeInstance)
		if **in != nil {
			in, out := *in, *out
			*out = make([]InputTypeInstance, len(*in))
			copy(*out, *in)
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ActionPolicy != nil {
		in, out := &in.ActionPolicy, &out.ActionPolicy
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedActionInput.
func (in *ResolvedActionInput) DeepCopy() *ResolvedActionInput {
	if in == nil {
		return nil
	}
	out := new(ResolvedActionInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerStatus) DeepCopyInto(out *RunnerStatus) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerStatus.
func (in *RunnerStatus) DeepCopy() *RunnerStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerStatus)
	in.DeepCopyInto(out)
	return out
}
