apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub.fullname" . }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.populator.enabled }}
        - name: "{{ .Chart.Name }}-populator"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.containerRegistry.path }}/{{ .Values.populator.image.name }}:{{ .Values.global.containerRegistry.overrideTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.populator.image.pullPolicy }}
          env:
            - name: APP_NEO4J_ADDR
              value: "{{ .Values.global.database.endpoint }}"
            - name: APP_NEO4J_USER
              value: "{{ .Values.global.database.username }}"
            - name: APP_NEO4J_PASSWORD
              value: "{{ .Values.global.database.password }}"
            - name: APP_JSON_PUBLISH_ADDR
              value: {{ printf "http://%s.%s" (include "hub.fullname" .) .Release.Namespace }}
            - name: APP_JSON_PUBLISH_PORT
              value: "{{ .Values.populator.port }}"
            - name: MANIFESTS_SOURCES
              value: "{{ include "populator.manifestSources" . }}"
            - name: APP_UPDATE_ON_GIT_COMMIT
              value: "{{ .Values.populator.updateOnGitCommit}}"

          command: ["/bin/sh", "-c"]
          args: {{ .Values.populator.args }}
          ports:
            - name: populator-port
              containerPort: {{ .Values.populator.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
     {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.containerRegistry.path }}/{{ .Values.image.name }}:{{ .Values.global.containerRegistry.overrideTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_GRAPH_QL_ADDR
              value: ":8080"
            - name: APP_HUB_MODE
              value: "public"
            - name: APP_LOGGER_DEV_MODE
              value: "true"
            - name: APP_NEO4J_ENDPOINT
              value: "{{ .Values.global.database.endpoint }}"
            - name: APP_NEO4J_USERNAME
              value: "{{ .Values.global.database.username }}"
            - name: APP_NEO4J_PASSWORD
              value: "{{ .Values.global.database.password }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
