env:
  node: true
  es2020: true
extends:
  - airbnb-base
  - prettier

parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
  - prettier
  - "@typescript-eslint"

settings:
  import/resolver:
    node:
      extensions: [".ts", ".js"]

rules:
  prettier/prettier: "error"
  import/extensions: ["off"]
  import/prefer-default-export: ["off"]
  no-use-before-define: ["error", { "functions": false }]
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
  no-shadow: "off"
  "@typescript-eslint/no-shadow": "error"
