issues:
  exclude:
    # Check this issue for more info: https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tc` in function literal
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # This is a special case. We want to have a different name for each Resolver
    # as we are using struct embedding pattern in root_resolver.go files. Each name needs
    # to be unique example:
    #  - typeinstance.Resolver == tags.Resolver (same field name in embedded struct)
    #  - typeinstance.TypeInstanceResolver != tags.TagResolver (diff field name in embedded struct)
    - path: internal/.*/graphql/.*resolver/.*.go
      text: "consider calling this Resolver"
      linters:
        - golint

run:
  tests: true
  skip-files:
    - ".*\\.gen\\.go$"
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - golint
    - gofmt
    - misspell
    - gochecknoinits
    - unparam
    - scopelint
    - gosec
    - goimports
    - whitespace
    - bodyclose
    - gocyclo

  fast: false
