# Release config.
# Diff to .goreleaser.latest.yml:
# - run before hook `make generate`
# - generate `386, amd64 and arm64` ARCH instead of amd64 only
# - upx compression set to 9 instead of 1
# - publish populator binary too
# - publish Docker images

before:
  hooks:
    - go mod tidy

builds:
  # Capact CLI
  - id: capact
    env: &build-env
      - CGO_ENABLED=0
    goos: &build-goos
      - linux
      - windows
      - darwin
    goarch: &build-arch
      - "386"
      - amd64
      - arm64
    ignore: &build-ignore
      # upx doesn't support packing Windows Arm64 binaries - see https://github.com/upx/upx/issues/551
      # once there is more demand from the community to build such binary, we will create a separate build config for this combination
      - goos: windows
        goarch: arm64
    hooks: &build-hooks
      post: ./hack/compress-release-binary.sh {{ .Path }}
    main: ./cmd/cli
    binary: "capact"
    ldflags:
      - -s -w -X  capact.io/capact/cmd/cli/cmd.Version={{.Version}} -X  capact.io/capact/cmd/cli/cmd.Revision={{.ShortCommit}} -X capact.io/capact/cmd/cli/cmd.BuildDate={{.Date}} -X capact.io/capact/cmd/cli/cmd.Branch={{.Branch}}

  # Capact populator
  - id: populator
    env: *build-env
    goos: *build-goos
    goarch: *build-arch
    ignore: *build-ignore
    hooks: *build-hooks
    main: ./cmd/populator
    binary: "populator"

archives:
  - id: capact-archive
    name_template: &archives-name-template "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: &archives-format binary
    builds:
      - capact

  - id: populator-archive
    name_template: *archives-name-template
    format: *archives-format
    builds:
      - populator

brews:
  - name: capact
    ids:
      - capact-archive
    homepage: &homebrew-homepage https://github.com/capactio/homebrew-tap
    description: "Capact CLI is a command-line tool, which manages Capact resources."
    license: "Apache License 2.0"
    tap: &homebrew-tap
      owner: capactio
      name: homebrew-tap
    commit_author: &homebrew-commit-author
      name: Capact Bot
      email: capactbot@capact.io
    test: |
      system "#{bin}/capact version"

  - name: populator
    ids:
      - populator-archive
    homepage: *homebrew-homepage
    description: "Populator is a command-line tool, which helps to populate various Capact content."
    license: "Apache License 2.0"
    tap: *homebrew-tap
    commit_author: *homebrew-commit-author
    test: |
      system "#{bin}/populator help"

dockers:
  - dockerfile: Dockerfile.cli
    ids:
      - capact
    image_templates:
      - "gcr.io/sm-cluster-dev/tools/capact-cli:stable"
      - "gcr.io/sm-cluster-dev/tools/capact-cli:{{ .Tag }}"
      - "gcr.io/sm-cluster-dev/tools/capact-cli:v{{ .Major }}.{{ .Minor }}"
      - "gcr.io/sm-cluster-dev/tools/capact-cli:v{{ .Major }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dist: bin

release:
  github:
    owner: capactio
    name: capact
