# Release config.
# Diff to .goreleaser.latest.yml:
# - run before hook `make generate`
# - generate `386, amd64 and arm64` ARCH instead of amd64 only
# - upx compression set to 9 instead of 1
# - publish populator binary too
# - publish Docker images

before:
  hooks:
    - go mod tidy

builds:
  # Capact CLI
  - id: capact
    env: &build-env
      - CGO_ENABLED=0
    goos: &build-goos
      - linux
      - windows
      - darwin
    hooks: &build-hooks
      # Install upx first, https://github.com/upx/upx/releases
      post: upx -9 "{{ .Path }}"
    main: ./cmd/cli
    binary: 'capact-{{ .Os }}-{{ .Arch }}'
    ldflags:
      - -s -w -X  capact.io/capact/cmd/cli/cmd.Version={{.Version}} -X  capact.io/capact/cmd/cli/cmd.Revision={{.ShortCommit}} -X capact.io/capact/cmd/cli/cmd.BuildDate={{.Date}} -X capact.io/capact/cmd/cli/cmd.Branch={{.Branch}}
    no_unique_dist_dir: true

  # Capact populator
  - id: populator
    env: *build-env
    goos: *build-goos
    hooks: *build-hooks
    main: ./cmd/populator
    binary: 'populator-{{ .Os }}-{{ .Arch }}'
    no_unique_dist_dir: true

archives:
  - format: binary
    name_template: '{{ .Binary }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'

dockers:
  - dockerfile: Dockerfile.cli
    ids:
      - capact
    image_templates:
      - "ghcr.io/capactio/tools/capact-cli:stable"
      - "ghcr.io/capactio/tools/capact-cli:{{ .Tag }}"
      - "ghcr.io/capactio/tools/capact-cli:v{{ .Major }}.{{ .Minor }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dist: bin

blobs:
  -
    provider: gs
    bucket: capactio-binaries
    folder: '{{ .Tag }}'

release:
  # You can disable this pipe in order to not upload any artifacts.
  # Defaults to false.
  disable: true
