before:
  hooks:
    - go mod tidy

builds:
  # Capact CLI
  - id: capact
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd/cli
    binary: 'capact'
    ldflags:
      - -s -w -X  capact.io/capact/cmd/cli/cmd.Version={{.Version}} -X  capact.io/capact/cmd/cli/cmd.Revision={{.ShortCommit}} -X capact.io/capact/cmd/cli/cmd.BuildDate={{.Date}} -X capact.io/capact/cmd/cli/cmd.Branch={{.Branch}}
    hooks:
      # Install upx first, https://github.com/upx/upx/releases
      post: upx -1 "{{ .Path }}"

archives:
  - format: binary
    name_template: '{{ .Binary }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'

dockers:
  - dockerfile: Dockerfile.cli
    ids:
      - capact
    image_templates:
      - "gcr.io/sm-cluster-dev/tools/capact-cli:latest"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dist: bin

release:
  # You can disable this pipe in order to not upload any artifacts.
  # Defaults to false.
  disable: true
