repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint and fix
        entry: make fix-lint-issues
        language: system
        always_run: true
        pass_filenames: false
      - id: unit-test
        name: Run unit tests
        entry: make test-unit
        language: system
        always_run: true
        pass_filenames: false
