apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: helm-poc
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: helm
            template: helm
            arguments:
              artifacts:
                - name: helm-args
                  raw:
                    data: |
                      context:
                        name: "helm-runner-example"
                        dryRun: false
                        timeout: "10m"
                        platform:
                          namespace: "default"
                          serviceAccountName: "helm-runner-example"
                      args:
                        command: "install"
                        generateName: true
                        chart:
                          name: "postgresql"
                          repo: "https://charts.bitnami.com/bitnami"
                        values:
                          image:
                            pullPolicy: Always
                          postgresqlDatabase: defaultdb
                          postgresqlPassword: okon
                        output:
                          directory: "/"
                          helmRelease:
                            fileName: "helm-release"
                          additional:
                            fileName: "additional"
                            value: |-
                              host: "{{ template "postgresql.fullname" . }}"
                              port: "{{ template "postgresql.port" . }}"
                              defaultDBName: "{{ template "postgresql.database" . }}"
                              superuser:
                                username: "{{ template "postgresql.username" . }}"
                                password: "{{ template "postgresql.password" . }}"
                                  template: helm

    - name: helm
      inputs:
        artifacts:
          - name: helm-args
            path: "/helm-args"
      outputs:
        artifacts:
          - name: helm-release
            path: "/helm-release"
          - name: additional
            path: "/additional"
      container:
        image: gcr.io/projectvoltron/helm-runner:de65286
        env:
          - name: RUNNER_INPUT_PATH
            value: "{{inputs.artifacts.helm-args.path}}"
