apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: helm-poc
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: helm-install
            action: # add template from helm-run
              name: cap.implementation.runner.helm.run
            arguments:
              artifacts:
                - name: helm-args
                  raw:
                    data: |
                      context:
                        name: "helm-runner-example"
                        dryRun: false
                        timeout: "10m"
                        platform:
                          namespace: "default"
                          serviceAccountName: "helm-runner-example"
                      args:
                        command: "install"
                        generateName: true
                        chart:
                          name: "postgresql"
                          repo: "https://charts.bitnami.com/bitnami"
                        values:
                          image:
                            pullPolicy: Always
                          postgresqlDatabase: defaultdb
                          postgresqlPassword: okon
                        output:
                          directory: "/"
                          helmRelease:
                            fileName: "helm-release"
                          additional:
                            fileName: "additional"
                            value: |-
                              host: "{{ template "postgresql.fullname" . }}"
                              port: "{{ template "postgresql.port" . }}"
                              defaultDBName: "{{ template "postgresql.database" . }}"
                              superuser:
                                username: "{{ template "postgresql.username" . }}"
                                password: "{{ template "postgresql.password" . }}"
                                  template: helm

        - - name: echo-outputs
            template: echo-outputs
            arguments:
              artifacts:
                - name: helm-release
                  from: "{{steps.helm-install.outputs.artifacts.helm-release}}"

    
    - name: echo-outputs