{{- $fullName := include "och.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "och.fullname" . }}
  labels:
    {{- include "och.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.annotations.class }}"  
    kubernetes.io/tls-acme: "{{ .Values.ingress.annotations.tls_acme }}"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.annotations.issuer }}"
    acmechallengetype: "{{ .Values.ingress.annotations.acmechallengetype }}"
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: 80
            path: {{ $.Values.ingress.path }}

    {{- end }}

