apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "och.fullname" . }}
  labels:
    {{- include "och.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "och.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "och.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "och.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.containerRegistry.path }}/{{ .Values.image.name }}:{{ .Values.global.containerRegistry.overrideTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_GRAPH_QL_ADDR
              value: ":8080"
            - name: APP_OCH_MODE
              value: "public"
            - name: APP_LOGGER_DEV_MODE
              value: "true"
            - name: APP_NEO4J_ENDPOINT
              value: "{{ .Values.global.database.endpoint }}"
            - name: APP_NEO4J_USERNAME
              value: "{{ .Values.global.database.username }}"
            - name: APP_NEO4J_PASSWORD
              value: "{{ .Values.global.database.password }}"
            - name: APP_MOCKGRAPHQL
              value: "{{ .Values.global.mockOCHGraphQL }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.global.mockOCHGraphQL }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
          {{- else }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
