# Let gqlgen know where to the generated models (if any)
model:
  package: graphql
  filename: ./models_gen.go # https://github.com/99designs/gqlgen/tree/master/plugin/modelgen

# Let gqlgenc know where to the generated client
client:
  package: graphql
  filename: ../../../client/public/generated/client.go # Where should any generated client go?

schema:
  - "../../../../../och-js/graphql/public/schema.graphql"
# Let gqlgenc know where all the query files located
query:
  - "../../../client/public/generated/queries.graphql" # Where are all the query files located? # Where are all the query files located?

models:
  Interface:
    fields:
      revision:
        resolver: true
  InterfaceGroup:
    fields:
      interfaces:
        resolver: true
  InterfaceRevision:
    fields:
      implementations:
        resolver: true
  Implementation:
    fields:
      revision:
        resolver: true
  ImplementationRevision:
    fields:
      interfaces:
        resolver: true
  Type:
    fields:
      revision:
        resolver: true
  Attribute:
    fields:
      revision:
        resolver: true
  RepoMetadata:
    fields:
      revision:
        resolver: true
