ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: database
  prefix: cap.type.database.postgresql  # Computed during fetching the manifest
  displayName: PostgreSQL Database
  description: Defines PostgreSQL database
  documentationURL: https://projectvoltron.dev
  supportURL: https://projectvoltron.dev
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for PostgreSQL database",
        "examples": [
          {
            "name": "dbName",
            "owner": "userName",
            "tablespace": "tablespace"
          }
        ],
        "required": [
            "name",
            "owner",
            "tablespace"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The DB name",
          },
          "owner": {
            "$id": "#/properties/owner",
            "type": "string",
            "title": "The DB owner username",
          },
          "tablespace": {
            "$id": "#/properties/tablespace",
            "type": "string",
            "title": "The DB tablespace",
          }
        },
        "additionalProperties": false
      }

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
