{{- if .Values.tlsCertificate.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsCertificate.name }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCertificate.crt | b64enc }}
  tls.key: {{ .Values.tlsCertificate.key | b64enc }}
{{- end }}
