kubed:
  config:
    clusterName: dev
    configSourceNamespace: argo
  # Do not send usage analytics
  enableAnalytics: false
  operator:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
