kubed:
  config:
    clusterName: stage
    configSourceNamespace: capact-system
  # Do not send usage analytics
  enableAnalytics: false
  operator:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
  podAnnotations:
    # `emptyDir` mounted to this Pod may prevent the k8s autoscaler to scale down the cluster
    # Read more here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
