kubed:
  config:
    clusterName: stage
    configSourceNamespace: capact-system
  # Do not send usage analytics
  enableAnalytics: false
  operator:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
