name: periodic-cluster-integration-tests
on:
  schedule:
  - cron: '0 */2 * * *'

jobs:
  integration-tests:
    name: Cluster integration tests
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GKE_CREDS }}
      - name: Get cluster credentials
        run: | 
          gcloud config set project ${PROJECT_ID}
          gcloud container clusters get-credentials ${TF_VAR_cluster_name} --zone=${TF_VAR_region}       
      - name: Network enable
        run: | 
          ./hack/ci/add-job-ip.sh
      - name: Save job ip
        uses: actions/upload-artifact@v1
        with:
          name: job_ip
          path: job_ip.sh
      - name: Test releases
        run: | 
          SERVICES=voltron
          for SERVICE in ${SERVICES}
          do  
            helm test ${SERVICE} --namespace=${NAMESPACE} --timeout=${HELM_TEST_TIMEOUT} --logs
          done


  network-cleanup:
    name: Network access cleanup
    runs-on: ubuntu-latest
    if: always()
    needs: [ integration-tests ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_CREDS }}
          export_default_credentials: true
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Download job ip
        uses: actions/download-artifact@v1
        with:
          name: job_ip
      - name: Network cleanup
        run: | 
          . job_ip/job_ip.sh
          ./hack/ci/remove-job-ip.sh
