// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package policy

import (
	"capact.io/capact/pkg/sdk/apis/0.0.1/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImplementationConstraints) DeepCopyInto(out *ImplementationConstraints) {
	*out = *in
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = new([]types.ManifestRef)
		if **in != nil {
			in, out := *in, *out
			*out = make([]types.ManifestRef, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new([]types.ManifestRef)
		if **in != nil {
			in, out := *in, *out
			*out = make([]types.ManifestRef, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImplementationConstraints.
func (in *ImplementationConstraints) DeepCopy() *ImplementationConstraints {
	if in == nil {
		return nil
	}
	out := new(ImplementationConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	in.ImplementationConstraints.DeepCopyInto(&out.ImplementationConstraints)
	if in.Inject != nil {
		in, out := &in.Inject, &out.Inject
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesForInterface) DeepCopyInto(out *RulesForInterface) {
	*out = *in
	in.Interface.DeepCopyInto(&out.Interface)
	if in.OneOf != nil {
		in, out := &in.OneOf, &out.OneOf
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesForInterface.
func (in *RulesForInterface) DeepCopy() *RulesForInterface {
	if in == nil {
		return nil
	}
	out := new(RulesForInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeInstanceToInject) DeepCopyInto(out *TypeInstanceToInject) {
	*out = *in
	in.TypeRef.DeepCopyInto(&out.TypeRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeInstanceToInject.
func (in *TypeInstanceToInject) DeepCopy() *TypeInstanceToInject {
	if in == nil {
		return nil
	}
	out := new(TypeInstanceToInject)
	in.DeepCopyInto(out)
	return out
}
