aws-for-fluent-bit:
  cloudWatch:
    region: eu-west-1
    logGroupName: /aws/eks/voltron-cluster/logs

  firehose:
    enabled: false

  kinesis:
    enabled: false

  elasticsearch:
    enabled: false
