// Package engine holds logic related to the Voltron engine. On root we should have only platform agnostic logic.
// All logic related to a given platform should be placed in a proper package, e.g. /engine/k8s/...
package engine
