# Copyright 2022 Nordcloud Oy or its affiliates. All Rights Reserved.

steps:
- script: |
    make build-all-images
  displayName: 'Build all images'

- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gcr-connection'

- script: |
    make push-all-images
  displayName: "Push all images"