ocfVersion: 0.0.1
revision: 0.1.0
kind: Implementation
metadata:
  prefix: cap.implementation.atlassian.jira # Computed during fetching the manifest
  name: install
  displayName: Install Jira
  description: Action which installs Jira via Helm chart
  documentationURL: https://github.com/javimox/helm-charts/tree/master/charts/jira-software
  supportURL: https://mox.sh/helm/
  license:
    name: "Apache 2.0"
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  appVersion: "8.x.x"

  additionalInput:
    typeInstances:
      postgresql:
        typeRef:
          path: cap.type.database.postgresql.config
          revision: 0.1.0
        verbs: [ "get" ]

  additionalOutput:
    typeInstanceRelations:
      jira-config:
        uses:
          - helm-release
          - postgresql

  implements:
    - path: cap.interface.productivity.jira.install
      revision: 0.1.0

  requires:
    cap.core.type.platform:
      oneOf:
        - name: kubernetes
          revision: 0.1.0

  imports:
    - interfaceGroupPath: cap.interface.runner.argo
      alias: argo
      methods:
        - name: run
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.runner.helm
      alias: helm
      appVersion: 3.x.x
      methods:
        - name: run
          revision: 0.1.0
    - interfaceGroupPath: cap.interface.database.postgresql
      alias: postgresql
      methods:
        - name: install
          revision: 0.1.0
        - name: create-db
          revision: 0.1.0

  action:
    runnerInterface: argo.run
    args:
      workflow:
        entrypoint: jira-install
        templates:
          - name: jira-install
            inputs:
              artifacts:
                - name: input-parameters
            steps:
              - - name: install-db
                  voltron-when: postgresql == nil # conditional execution
                  arguments:
                    artifacts:
                      - name: input-parameters
                        raw:
                          data: |
                            superuser:
                              username: jira
                              password: okon
                            defaultDBName: jira
                  voltron-action:
                    path: cap.interface.database.postgresql.install

              - - name: create-helm-args
                  voltron-action:
                    path: cap.interface.jinja2.template
                  arguments:
                    artifacts:
                      - name: template
                        raw:
                          data: |
                            context:
                              name: "helm-runner-example"
                              dryRun: false
                              timeout: "10m"
                              platform:
                                namespace: "default"
                                serviceAccountName: "helm-runner-example"
                            args:
                              command: "install"
                              generateName: true
                              chart:
                                name: "jira-software"
                                repo: "https://helm.mox.sh"
                              output:{% raw %}
                                directory: "/"
                                helmRelease:
                                  fileName: "helm-release"
                                additional:
                                  fileName: "additional"
                                  value: |-
                                    version: "{{ .Values.image.tag }}"
                                    host: "{{ template "jira-software.fullname" . }}"{% endraw %}
                              values:
                                postgresql:
                                  enabled: false
                                databaseConnection:
                                  host: "{{ host }}"
                                  user: "{{ superuser.username }}"
                                  password: "{{ superuser.password }}"
                                  database: "{{ defaultDBName }}"
                                ingress:
                                  enabled: true
                                  hosts:
                                  - host: jira-cloud.voltron.local
                                    paths: ['/']
                      - name: input-parameters
                        from: "{{workflow.outputs.artifacts.postgresql}}"

              - - name: helm-run
                  voltron-action:
                    path: cap.interface.runner.helm.run
                  voltron-outputTypeInstances:
                    - name: jira-config
                      from: additional
                    - name: helm-release
                      from: helm-release
                  arguments:
                    artifacts:
                      - name: input-parameters
                        from: "{{steps.create-helm-args.outputs.artifacts.render}}"

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
