ingress-nginx:
  # Copied from https://github.com/kubernetes/ingress-nginx/blob/master/hack/generate-deploy-scripts.sh#L125
  controller:
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    hostPort:
      enabled: true
    terminationGracePeriodSeconds: 0
    service:
      type: NodePort
    nodeSelector:
      ingress-ready: "true"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
    publishService:
      enabled: false
    extraArgs:
      publish-status-address: localhost
      default-ssl-certificate: "ingress-nginx/default-ssl-cert"
    config:
      ssl-redirect: "true"
      force-ssl-redirect: "true" # To enable HTTPS redirect with default SSL certificate

tlsCertificate:
  create: true
  # To regenerate the self-signed certificate, use command `openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout domain.key -out domain.crt -subj "/CN=voltron.local/O=Voltron`
  crt: "MIIC0DCCAbgCCQC5tgNlmgq9YjANBgkqhkiG9w0BAQsFADAqMRYwFAYDVQQDDA12b2x0cm9uLmxvY2FsMRAwDgYDVQQKDAdWb2x0cm9uMB4XDTIwMTEwMzA4MjEyOVoXDTMwMTEwMTA4MjEyOVowKjEWMBQGA1UEAwwNdm9sdHJvbi5sb2NhbDEQMA4GA1UECgwHVm9sdHJvbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM2iSQsMtaMVl7hY8PXplRgJLbHSGV8g9Zh8f/WT1+yHDDUnwwzCbfGSOTfYk5y/9kauY6AFUqQNjqDDoOftk8YPKLDektwWL2nrZmHszmgiUNN6LMgikM9Ry6vmvraBgtMlaTTpehJ6K6SzKI6JlPPKVRaFbzqrDD/RIFTbXwo/TPObBPJaY8SF6V1iuDpbXGFZlxhqdda5DjhhgUUNEY2VeS4K/jOj2C0CCzcDYiPaEU8jd3eJmU4MgPs3aDdF11VrY+TwMsZG1Bo7iioMrnjaIn4wLtasc1E7ufl4JLoN+C2Gg9wHKDb/VJYq3Q9ovi3zGcPb0nnghlQbcmqcP18CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAOo0zzjwv4pf3p52ARGVobC8plisxodgSvnkVt4PuDvyGz4jiFIVXci6RE/6tHYTiq3KImrXu3OS+lBi7EwUR/pKm6IOpvUqfpKUmICwbVXC9OjGwefdlBNzOsevWbSvPjx61CzzpWabYNk69f6RFAepYvH/l9lnQfRd8fIIlBKmqBCm8RSCrYvxAKw2Bqp6Nb4oDfFw7w3oPMZrwQLorXKTgNWfJhXbamqM20fNq/25xEwqNpG7CODY+Qrs8N6KKZUbQoQx/WGAkFBgnQIDvxB8oRZ7KwqVdCELhWRCKcHCsQXfaq5bVgS48sEbzvn3QwbXZCYfVTaCEzil0NXKc2w=="
  key: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDNokkLDLWjFZe4WPD16ZUYCS2x0hlfIPWYfH/1k9fshww1J8MMwm3xkjk32JOcv/ZGrmOgBVKkDY6gw6Dn7ZPGDyiw3pLcFi9p62Zh7M5oIlDTeizIIpDPUcur5r62gYLTJWk06XoSeiuksyiOiZTzylUWhW86qww/0SBU218KP0zzmwTyWmPEheldYrg6W1xhWZcYanXWuQ44YYFFDRGNlXkuCv4zo9gtAgs3A2Ij2hFPI3d3iZlODID7N2g3RddVa2Pk8DLGRtQaO4oqDK542iJ+MC7WrHNRO7n5eCS6DfgthoPcByg2/1SWKt0PaL4t8xnD29J54IZUG3JqnD9fAgMBAAECggEAG1Ko6fLyX40K78/BlKtIyDzP+YS1IlK6z1wblIHkeuUm1hlGbXeYLDUFrUn1syo+iv249xY9+NZkUTAtPSPwMqzo9zdbxCqeejBxFink8yk8HB1rvdv56dIwgdLTHGTxASVDaWhsc/APxH6ZsPbO9+W2kJuCQAViR0h+R0guxKmPUxYuDoQyZR3kfp92CEqHZQiupHzWRSMqpY/l1/IjZULqoPIZ85MYwF7xzirtr0lEeqo1llkZg/3TyOaw/Mhy4pxMMP5r8LyLtc1YpWRj678TKEDA6WGpmJHaAAi3MTJRpuaDJYEO+JBFYGxOaWtufCq+bdBENHBFp3S7qkw3oQKBgQD7KE2s+DAwyNdJNmzB9oCaFoBWbPbLO0xexZaAoD/f9ftZEKK/FbHHQ8P+SYxs3YUL9ukT/E1N009C/ZlKses8SgdXCkzajR5rrivgq73UzZziSE55Vx1wbBy3VYlA4hsCk2IxRUd3+U97VtN1DavCTEhGZrtmAKc75eXOcE8DgwKBgQDRmUfmmNlizgwuqOcCJjRfwyTf2zW7P06Wf0z11G1f8QW57jsfjYKyJZOYIAITMiMM/XwdnWBIRbleP6HSoS5mghDyeaojNqyRvu7mNV6vzUDPk30D3ru6Cg/D6Gj5bKjo3cDHW7YIJyGfItWeKps8zf49iKynIbh3AZnbCi4h9QKBgA12fptr/mFPEsM46KGJDiG0XRLE6oHAXvqhiszASkw+Ckge7SpjBlGRH1ttI9reEPiwNpQ8rQQj9Ja5s1LesKZdrYEL60y3zc6l2nJDonxavTMf/xzf/5L8KJnnOuFAfYQo1FWhyg/zTEBnShR3NCLJJgKoFRmFpXE/hI8JVCLzAoGBAJIbzPBlupxS0FEycp6f7UCYMztNfz5BWlI0+XwgkgIgbQJ4nIRZTDNNWH7iSTACckaa6YtnanfXCuo1Z2QB8euJXbD5uO2FLnUG6VhW+eOJLFXHFY2+FZURcH37pDnDUlfKRZlzSAiU5q4dRVZVkxOm8UUJ4nk7W3CyEAOOLCyFAoGBAI8lOIZOAgICqfR9bfjhCdRP3Q7wDhgpevKUHyo4YRdcd22sSgv6E93OAzVkjzcyYTP5d/bIAQn0W3bIMVxKyeksL00ejxB/BiSqTTKg6bK2sd3Q7iQ0vbwDXJ/5FJWSlDML7ixTGagjrrTtJcLmhXYpxzj1ew8dTzEpBY1pKL5n"


