apiVersion: core.projectvoltron.dev/v1alpha1
kind: Action
metadata:
  name: "full-spec"
spec:
  actionRef:
    path: "cap.interface.productivity.jira.install"
    revision: "0.1.0"
  input:
    parameters:
      secretRef:
        name: "full-spec-params"
    typeInstances:
      - name: foo
        id: fee33a5e-d957-488a-86bd-5dacd4120312
      - name: bar
        id: 563a79eb-7417-4e11-aa4b-d93076c04e48
  advancedRendering:
    enabled: true
    renderingIteration:
      approvedIterationName: postgresql-install
  run: false
  dryRun: false
  cancel: false
