apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: hosting@qqq.org
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53: #TODO parameterize this based on terraform output
            region: eu-west-1
            hostedZoneID: Z0827236UIU0MQ3RH1IG
