ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.runner.argo
  name: run
  displayName: "Run"
  description: "Run action for Argo Runner"
  documentationURL: https://projectvoltron.dev
  supportURL: https://projectvoltron.dev
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  abstract: true # It cannot be implemented
  input:
    parameters:
      input-parameters:
        jsonSchema:
          value: |-
            {
              "$schema": "http://json-schema.org/draft-07/schema",
              "$ocfRefs": {
                "inputType": {
                  "name": "cap.type.runner.argo.run-input",
                  "revision": "0.1.0"
                }
              },
              "allOf": [ { "$ref": "#/$ocfRefs/inputType" } ]
            }
    typeInstances:
      runner-context:
        typeRef:
          path: cap.core.type.runner.generic.context
          revision: 0.1.0
        verbs: [ "get" ]
  output: {}

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
