apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.gateway.auth.username }}
  password: {{ .Values.global.gateway.auth.password }}
