ocfVersion: 0.0.1
revision: 0.1.0
kind: InterfaceGroup
metadata:
  prefix: cap.interface.productivity # Computed during fetching the manifest
  name: stack
  displayName: "Atlassian stack installation"
  description: "Installs Jira and Confluence with shared database."
  documentationURL: https://support.atlassian.com
  supportURL: https://www.atlassian.com
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
