ocfVersion: 0.0.1
revision: 0.1.0
kind: InterfaceGroup
metadata:
  prefix: cap.interface.atlassian
  name: stack
  displayName: "Atlassian stack"
  description: "Atlassian app bundle"
  documentationURL: https://support.atlassian.com
  supportURL: https://www.atlassian.com
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
