ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.<%=categoryName%>.<%=baseName%>
  displayName: <%=capBaseName%> config
  description: Defines configuration for <%=capBaseName%> instance
  documentationURL: <%=documentationURL%>
  supportURL: <%=supportURL%>
  iconURL: <%=iconURL%>
  maintainers:
    - email: "<%=maintainerEmail%>"
      name: "<%=maintainerName%>"
      url: "<%=maintainerURL%>"

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for <%=capBaseName%> configuration",
        "required": [
            "version"
        ],
        "$ocfRefs": {
          "semVer": {
            "name": "cap.core.type.versioning.semver",
            "revision": "0.1.0"
          }
          "hostname": {
            "name": "cap.core.type.networking.hostname",
            "revision": "0.1.0"
          }
        },
        "properties": {
          "version": {
            "$ref": "#/$ocfRefs/semVer"
          }
          "host": {
            "$ref": "#/$ocfRefs/hostname"
          }
        },
        "additionalProperties": true
      }

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
