# permissions for end users to view composers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composer-viewer-role
rules:
- apiGroups:
  - core.capact.io
  resources:
  - composers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.capact.io
  resources:
  - composers/status
  verbs:
  - get
