// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: storage_backend.proto

package storage_backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValueAndContextStorageBackendClient is the client API for ValueAndContextStorageBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValueAndContextStorageBackendClient interface {
	// value
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	OnCreate(ctx context.Context, in *OnCreateValueAndContextRequest, opts ...grpc.CallOption) (*OnCreateResponse, error)
	OnUpdate(ctx context.Context, in *OnUpdateValueAndContextRequest, opts ...grpc.CallOption) (*OnUpdateResponse, error)
	OnDelete(ctx context.Context, in *OnDeleteValueAndContextRequest, opts ...grpc.CallOption) (*OnDeleteResponse, error)
	// lock
	GetLockedBy(ctx context.Context, in *GetLockedByRequest, opts ...grpc.CallOption) (*GetLockedByResponse, error)
	OnLock(ctx context.Context, in *OnLockRequest, opts ...grpc.CallOption) (*OnLockResponse, error)
	OnUnlock(ctx context.Context, in *OnUnlockRequest, opts ...grpc.CallOption) (*OnUnlockResponse, error)
}

type valueAndContextStorageBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewValueAndContextStorageBackendClient(cc grpc.ClientConnInterface) ValueAndContextStorageBackendClient {
	return &valueAndContextStorageBackendClient{cc}
}

func (c *valueAndContextStorageBackendClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueAndContextStorageBackendClient) OnCreate(ctx context.Context, in *OnCreateValueAndContextRequest, opts ...grpc.CallOption) (*OnCreateResponse, error) {
	out := new(OnCreateResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/OnCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueAndContextStorageBackendClient) OnUpdate(ctx context.Context, in *OnUpdateValueAndContextRequest, opts ...grpc.CallOption) (*OnUpdateResponse, error) {
	out := new(OnUpdateResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/OnUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueAndContextStorageBackendClient) OnDelete(ctx context.Context, in *OnDeleteValueAndContextRequest, opts ...grpc.CallOption) (*OnDeleteResponse, error) {
	out := new(OnDeleteResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/OnDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueAndContextStorageBackendClient) GetLockedBy(ctx context.Context, in *GetLockedByRequest, opts ...grpc.CallOption) (*GetLockedByResponse, error) {
	out := new(GetLockedByResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/GetLockedBy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueAndContextStorageBackendClient) OnLock(ctx context.Context, in *OnLockRequest, opts ...grpc.CallOption) (*OnLockResponse, error) {
	out := new(OnLockResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/OnLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valueAndContextStorageBackendClient) OnUnlock(ctx context.Context, in *OnUnlockRequest, opts ...grpc.CallOption) (*OnUnlockResponse, error) {
	out := new(OnUnlockResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ValueAndContextStorageBackend/OnUnlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValueAndContextStorageBackendServer is the server API for ValueAndContextStorageBackend service.
// All implementations must embed UnimplementedValueAndContextStorageBackendServer
// for forward compatibility
type ValueAndContextStorageBackendServer interface {
	// value
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	OnCreate(context.Context, *OnCreateValueAndContextRequest) (*OnCreateResponse, error)
	OnUpdate(context.Context, *OnUpdateValueAndContextRequest) (*OnUpdateResponse, error)
	OnDelete(context.Context, *OnDeleteValueAndContextRequest) (*OnDeleteResponse, error)
	// lock
	GetLockedBy(context.Context, *GetLockedByRequest) (*GetLockedByResponse, error)
	OnLock(context.Context, *OnLockRequest) (*OnLockResponse, error)
	OnUnlock(context.Context, *OnUnlockRequest) (*OnUnlockResponse, error)
	mustEmbedUnimplementedValueAndContextStorageBackendServer()
}

// UnimplementedValueAndContextStorageBackendServer must be embedded to have forward compatible implementations.
type UnimplementedValueAndContextStorageBackendServer struct {
}

func (UnimplementedValueAndContextStorageBackendServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) OnCreate(context.Context, *OnCreateValueAndContextRequest) (*OnCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCreate not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) OnUpdate(context.Context, *OnUpdateValueAndContextRequest) (*OnUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnUpdate not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) OnDelete(context.Context, *OnDeleteValueAndContextRequest) (*OnDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnDelete not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) GetLockedBy(context.Context, *GetLockedByRequest) (*GetLockedByResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLockedBy not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) OnLock(context.Context, *OnLockRequest) (*OnLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnLock not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) OnUnlock(context.Context, *OnUnlockRequest) (*OnUnlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnUnlock not implemented")
}
func (UnimplementedValueAndContextStorageBackendServer) mustEmbedUnimplementedValueAndContextStorageBackendServer() {
}

// UnsafeValueAndContextStorageBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValueAndContextStorageBackendServer will
// result in compilation errors.
type UnsafeValueAndContextStorageBackendServer interface {
	mustEmbedUnimplementedValueAndContextStorageBackendServer()
}

func RegisterValueAndContextStorageBackendServer(s grpc.ServiceRegistrar, srv ValueAndContextStorageBackendServer) {
	s.RegisterService(&ValueAndContextStorageBackend_ServiceDesc, srv)
}

func _ValueAndContextStorageBackend_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueAndContextStorageBackend_OnCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCreateValueAndContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).OnCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/OnCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).OnCreate(ctx, req.(*OnCreateValueAndContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueAndContextStorageBackend_OnUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnUpdateValueAndContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).OnUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/OnUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).OnUpdate(ctx, req.(*OnUpdateValueAndContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueAndContextStorageBackend_OnDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnDeleteValueAndContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).OnDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/OnDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).OnDelete(ctx, req.(*OnDeleteValueAndContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueAndContextStorageBackend_GetLockedBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLockedByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).GetLockedBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/GetLockedBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).GetLockedBy(ctx, req.(*GetLockedByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueAndContextStorageBackend_OnLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).OnLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/OnLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).OnLock(ctx, req.(*OnLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValueAndContextStorageBackend_OnUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValueAndContextStorageBackendServer).OnUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ValueAndContextStorageBackend/OnUnlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValueAndContextStorageBackendServer).OnUnlock(ctx, req.(*OnUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValueAndContextStorageBackend_ServiceDesc is the grpc.ServiceDesc for ValueAndContextStorageBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValueAndContextStorageBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage_backend.ValueAndContextStorageBackend",
	HandlerType: (*ValueAndContextStorageBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _ValueAndContextStorageBackend_GetValue_Handler,
		},
		{
			MethodName: "OnCreate",
			Handler:    _ValueAndContextStorageBackend_OnCreate_Handler,
		},
		{
			MethodName: "OnUpdate",
			Handler:    _ValueAndContextStorageBackend_OnUpdate_Handler,
		},
		{
			MethodName: "OnDelete",
			Handler:    _ValueAndContextStorageBackend_OnDelete_Handler,
		},
		{
			MethodName: "GetLockedBy",
			Handler:    _ValueAndContextStorageBackend_GetLockedBy_Handler,
		},
		{
			MethodName: "OnLock",
			Handler:    _ValueAndContextStorageBackend_OnLock_Handler,
		},
		{
			MethodName: "OnUnlock",
			Handler:    _ValueAndContextStorageBackend_OnUnlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage_backend.proto",
}

// ContextStorageBackendClient is the client API for ContextStorageBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextStorageBackendClient interface {
	//value
	GetPreCreateValue(ctx context.Context, in *GetPreCreateValueRequest, opts ...grpc.CallOption) (*GetPreCreateValueResponse, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	OnCreate(ctx context.Context, in *OnCreateRequest, opts ...grpc.CallOption) (*OnCreateResponse, error)
	OnUpdate(ctx context.Context, in *OnUpdateRequest, opts ...grpc.CallOption) (*OnUpdateResponse, error)
	OnDelete(ctx context.Context, in *OnDeleteRequest, opts ...grpc.CallOption) (*OnDeleteResponse, error)
	OnDeleteRevision(ctx context.Context, in *OnDeleteRevisionRequest, opts ...grpc.CallOption) (*OnDeleteRevisionResponse, error)
	// lock
	GetLockedBy(ctx context.Context, in *GetLockedByRequest, opts ...grpc.CallOption) (*GetLockedByResponse, error)
	OnLock(ctx context.Context, in *OnLockRequest, opts ...grpc.CallOption) (*OnLockResponse, error)
	OnUnlock(ctx context.Context, in *OnUnlockRequest, opts ...grpc.CallOption) (*OnUnlockResponse, error)
}

type contextStorageBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewContextStorageBackendClient(cc grpc.ClientConnInterface) ContextStorageBackendClient {
	return &contextStorageBackendClient{cc}
}

func (c *contextStorageBackendClient) GetPreCreateValue(ctx context.Context, in *GetPreCreateValueRequest, opts ...grpc.CallOption) (*GetPreCreateValueResponse, error) {
	out := new(GetPreCreateValueResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/GetPreCreateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) OnCreate(ctx context.Context, in *OnCreateRequest, opts ...grpc.CallOption) (*OnCreateResponse, error) {
	out := new(OnCreateResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/OnCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) OnUpdate(ctx context.Context, in *OnUpdateRequest, opts ...grpc.CallOption) (*OnUpdateResponse, error) {
	out := new(OnUpdateResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/OnUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) OnDelete(ctx context.Context, in *OnDeleteRequest, opts ...grpc.CallOption) (*OnDeleteResponse, error) {
	out := new(OnDeleteResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/OnDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) OnDeleteRevision(ctx context.Context, in *OnDeleteRevisionRequest, opts ...grpc.CallOption) (*OnDeleteRevisionResponse, error) {
	out := new(OnDeleteRevisionResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/OnDeleteRevision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) GetLockedBy(ctx context.Context, in *GetLockedByRequest, opts ...grpc.CallOption) (*GetLockedByResponse, error) {
	out := new(GetLockedByResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/GetLockedBy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) OnLock(ctx context.Context, in *OnLockRequest, opts ...grpc.CallOption) (*OnLockResponse, error) {
	out := new(OnLockResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/OnLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextStorageBackendClient) OnUnlock(ctx context.Context, in *OnUnlockRequest, opts ...grpc.CallOption) (*OnUnlockResponse, error) {
	out := new(OnUnlockResponse)
	err := c.cc.Invoke(ctx, "/storage_backend.ContextStorageBackend/OnUnlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextStorageBackendServer is the server API for ContextStorageBackend service.
// All implementations must embed UnimplementedContextStorageBackendServer
// for forward compatibility
type ContextStorageBackendServer interface {
	//value
	GetPreCreateValue(context.Context, *GetPreCreateValueRequest) (*GetPreCreateValueResponse, error)
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	OnCreate(context.Context, *OnCreateRequest) (*OnCreateResponse, error)
	OnUpdate(context.Context, *OnUpdateRequest) (*OnUpdateResponse, error)
	OnDelete(context.Context, *OnDeleteRequest) (*OnDeleteResponse, error)
	OnDeleteRevision(context.Context, *OnDeleteRevisionRequest) (*OnDeleteRevisionResponse, error)
	// lock
	GetLockedBy(context.Context, *GetLockedByRequest) (*GetLockedByResponse, error)
	OnLock(context.Context, *OnLockRequest) (*OnLockResponse, error)
	OnUnlock(context.Context, *OnUnlockRequest) (*OnUnlockResponse, error)
	mustEmbedUnimplementedContextStorageBackendServer()
}

// UnimplementedContextStorageBackendServer must be embedded to have forward compatible implementations.
type UnimplementedContextStorageBackendServer struct {
}

func (UnimplementedContextStorageBackendServer) GetPreCreateValue(context.Context, *GetPreCreateValueRequest) (*GetPreCreateValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreCreateValue not implemented")
}
func (UnimplementedContextStorageBackendServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedContextStorageBackendServer) OnCreate(context.Context, *OnCreateRequest) (*OnCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCreate not implemented")
}
func (UnimplementedContextStorageBackendServer) OnUpdate(context.Context, *OnUpdateRequest) (*OnUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnUpdate not implemented")
}
func (UnimplementedContextStorageBackendServer) OnDelete(context.Context, *OnDeleteRequest) (*OnDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnDelete not implemented")
}
func (UnimplementedContextStorageBackendServer) OnDeleteRevision(context.Context, *OnDeleteRevisionRequest) (*OnDeleteRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnDeleteRevision not implemented")
}
func (UnimplementedContextStorageBackendServer) GetLockedBy(context.Context, *GetLockedByRequest) (*GetLockedByResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLockedBy not implemented")
}
func (UnimplementedContextStorageBackendServer) OnLock(context.Context, *OnLockRequest) (*OnLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnLock not implemented")
}
func (UnimplementedContextStorageBackendServer) OnUnlock(context.Context, *OnUnlockRequest) (*OnUnlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnUnlock not implemented")
}
func (UnimplementedContextStorageBackendServer) mustEmbedUnimplementedContextStorageBackendServer() {}

// UnsafeContextStorageBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextStorageBackendServer will
// result in compilation errors.
type UnsafeContextStorageBackendServer interface {
	mustEmbedUnimplementedContextStorageBackendServer()
}

func RegisterContextStorageBackendServer(s grpc.ServiceRegistrar, srv ContextStorageBackendServer) {
	s.RegisterService(&ContextStorageBackend_ServiceDesc, srv)
}

func _ContextStorageBackend_GetPreCreateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreCreateValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).GetPreCreateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/GetPreCreateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).GetPreCreateValue(ctx, req.(*GetPreCreateValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_OnCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).OnCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/OnCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).OnCreate(ctx, req.(*OnCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_OnUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).OnUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/OnUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).OnUpdate(ctx, req.(*OnUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_OnDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).OnDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/OnDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).OnDelete(ctx, req.(*OnDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_OnDeleteRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnDeleteRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).OnDeleteRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/OnDeleteRevision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).OnDeleteRevision(ctx, req.(*OnDeleteRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_GetLockedBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLockedByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).GetLockedBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/GetLockedBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).GetLockedBy(ctx, req.(*GetLockedByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_OnLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).OnLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/OnLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).OnLock(ctx, req.(*OnLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContextStorageBackend_OnUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextStorageBackendServer).OnUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_backend.ContextStorageBackend/OnUnlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextStorageBackendServer).OnUnlock(ctx, req.(*OnUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextStorageBackend_ServiceDesc is the grpc.ServiceDesc for ContextStorageBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextStorageBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage_backend.ContextStorageBackend",
	HandlerType: (*ContextStorageBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPreCreateValue",
			Handler:    _ContextStorageBackend_GetPreCreateValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _ContextStorageBackend_GetValue_Handler,
		},
		{
			MethodName: "OnCreate",
			Handler:    _ContextStorageBackend_OnCreate_Handler,
		},
		{
			MethodName: "OnUpdate",
			Handler:    _ContextStorageBackend_OnUpdate_Handler,
		},
		{
			MethodName: "OnDelete",
			Handler:    _ContextStorageBackend_OnDelete_Handler,
		},
		{
			MethodName: "OnDeleteRevision",
			Handler:    _ContextStorageBackend_OnDeleteRevision_Handler,
		},
		{
			MethodName: "GetLockedBy",
			Handler:    _ContextStorageBackend_GetLockedBy_Handler,
		},
		{
			MethodName: "OnLock",
			Handler:    _ContextStorageBackend_OnLock_Handler,
		},
		{
			MethodName: "OnUnlock",
			Handler:    _ContextStorageBackend_OnUnlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage_backend.proto",
}
