apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}-cluster-policy
  labels:
  {{- include "engine.labels" . | nindent 4 }}
data:
  cluster-policy.yaml: |
		{{- toYaml .Values.globalPolicy | nindent 4 }}
