{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
# Dedicated Service for metrics endpoint
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "engine.fullname" . }}-controller"
  labels:
  {{- include "engine.labels" . | nindent 4 }}
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.controller.metricsPort }}
  selector:
    {{- include "engine.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "engine.fullname" . }}-controller"
  labels:
    capact.io/scrape-metrics: "true"
    {{- include "engine.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http-metrics
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "engine.selectorLabels" . | nindent 6 }}
{{- end }}
