ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.runner.helm
  name: upgrade
  displayName: "Upgrade"
  description: "Upgrade action for Helm Runner"
  documentationURL: https://projectvoltron.dev
  supportURL: https://projectvoltron.dev
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  input:
    parameters:
      input-parameters:
        jsonSchema:
          value: |-
            {
              "$schema": "http://json-schema.org/draft-07/schema",
              "$ocfRefs": {
                "inputType": {
                  "name": "cap.type.runner.helm.upgrade-input",
                  "revision": "0.1.0"
                }
              },
              "allOf": [ { "$ref": "#/$ocfRefs/inputType" } ]
            }
    typeInstances:
      runner-context:
        typeRef:
          path: cap.core.type.runner.generic.context
          revision: 0.1.0
        verbs: [ "get" ]
      helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
        verbs: [ "get", "update" ]
  output:
    typeInstances:
      helm-release:
        typeRef:
          path: cap.type.helm.chart.release
          revision: 0.1.0
      additional:
        typeRef:
          path: cap.core.type.generic.value
          revision: 0.1.0

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
