apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: jira-with-postgres
spec:
  arguments:
    artifacts:
    - name: input-parameters
      raw:
        data: |
          {}
  entrypoint: jira-install
  templates:
  - inputs:
      artifacts:
      - name: input-parameters
    name: jira-install
    outputs: {}
    steps:
    - - arguments:
          artifacts:
          - name: input-parameters
            raw:
              data: |
                superuser:
                  username: jira
                  password: okon
                defaultDBName: jira
        name: install-db
        template: jira-install-install-db-postgres-install
    - - arguments:
          artifacts:
          - name: template
            raw:
              data: |
                context:
                  name: "helm-runner-example"
                  dryRun: false
                  timeout: "10m"
                  platform:
                    namespace: "default"
                    serviceAccountName: "helm-runner-example"
                args:
                  command: "install"
                  generateName: true
                  chart:
                    name: "jira-software"
                    repo: "https://helm.mox.sh"
                  output:{% raw %}
                    directory: "/"
                    helmRelease:
                      fileName: "helm-release"
                    additional:
                      fileName: "additional"
                      value: |-
                        version: "{{ .Values.image.tag }}"
                        host: "{{ template "jira-software.fullname" . }}"{% endraw %}
                  values:
                    postgresql:
                      enabled: false
                    databaseConnection:
                      host: "{{ host }}"
                      user: "{{ superuser.username }}"
                      password: "{{ superuser.password }}"
                      database: "{{ defaultDBName }}"
                    ingress:
                      enabled: true
                      hosts:
                      - host: jira-cloud.voltron.local
                        paths: ['/']
          - from: '{{workflow.outputs.artifacts.jira-install-install-db-postgresql}}'
            name: input-parameters
        name: create-helm-args
        template: jira-install-create-helm-args-template
    - - arguments:
          artifacts:
          - from: '{{steps.create-helm-args.outputs.artifacts.render}}'
            name: input-parameters
        name: helm-run
        template: jira-install-helm-run-helm
    - - arguments:
          artifacts:
          - from: '{{steps.helm-run.outputs.artifacts.additional}}'
            name: jira-config
        name: output-jira-config
        template: output-jira-config
  - container:
      args:
      - sleep 1
      command:
      - sh
      - -c
      image: alpine:3.7
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: jira-config
        path: /typeinstance
    name: output-jira-config
    outputs:
      artifacts:
      - globalName: jira-config
        name: jira-config
        path: /typeinstance
  - inputs:
      artifacts:
      - name: input-parameters
    name: jira-install-install-db-postgres-install
    outputs: {}
    steps:
    - - arguments:
          artifacts:
          - from: '{{inputs.artifacts.input-parameters}}'
            name: input-parameters
          - name: template
            raw:
              data: |
                context:
                  name: "helm-runner-example"
                  dryRun: false
                  timeout: "10m"
                  platform:
                    namespace: "default"
                    serviceAccountName: "helm-runner-example"
                args:
                  command: "install"
                  generateName: true
                  chart:
                    name: "postgresql"
                    repo: "https://charts.bitnami.com/bitnami"
                  values:
                    image:
                      pullPolicy: Always
                    postgresqlDatabase: {{ defaultDBName }}
                    postgresqlUsername: {{ superuser.username }}
                    postgresqlPassword: {{ superuser.password }}
                  output:{% raw %}
                    directory: "/"
                    helmRelease:
                      fileName: "helm-release"
                    additional:
                      fileName: "additional"
                      value: |-
                        host: "{{ template "common.names.fullname" . }}"
                        port: "{{ template "postgresql.port" . }}"
                        defaultDBName: "{{ template "postgresql.database" . }}"
                        superuser:
                          username: "{{ template "postgresql.username" . }}"
                          password: "{{ template "postgresql.password" . }}"{% endraw %}
        name: create-helm-args
        template: jira-install-install-db-postgres-install-create-helm-args-template
    - - arguments:
          artifacts:
          - from: '{{steps.create-helm-args.outputs.artifacts.render}}'
            name: input-parameters
        name: helm-run
        template: jira-install-install-db-postgres-install-helm-run-helm
    - - arguments:
          artifacts:
          - from: '{{steps.helm-run.outputs.artifacts.additional}}'
            name: postgresql
        name: output-postgresql
        template: jira-install-install-db-output-postgresql
  - container:
      args:
      - sleep 1
      command:
      - sh
      - -c
      image: alpine:3.7
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: postgresql
        path: /typeinstance
    name: jira-install-install-db-output-postgresql
    outputs:
      artifacts:
      - globalName: jira-install-install-db-postgresql
        name: postgresql
        path: /typeinstance
  - container:
      args:
      - /template.yml
      - /values.yml
      - --format=yaml
      - -o
      - /render.yml
      image: dinutac/jinja2docker
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: template
        path: /template.yml
      - name: input-parameters
        path: /values.yml
    name: jira-install-create-helm-args-template
    outputs:
      artifacts:
      - name: render
        path: /render.yml
  - container:
      env:
      - name: RUNNER_INPUT_PATH
        value: '{{inputs.artifacts.input-parameters.path}}'
      image: gcr.io/projectvoltron/helm-runner:de65286
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: input-parameters
        path: /helm-args
    name: jira-install-helm-run-helm
    outputs:
      artifacts:
      - globalName: jira-install-helm-run-helm-release
        name: helm-release
        path: /helm-release
      - globalName: jira-install-helm-run-additional
        name: additional
        path: /additional
  - container:
      args:
      - /template.yml
      - /values.yml
      - --format=yaml
      - -o
      - /render.yml
      image: dinutac/jinja2docker
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: template
        path: /template.yml
      - name: input-parameters
        path: /values.yml
    name: jira-install-install-db-postgres-install-create-helm-args-template
    outputs:
      artifacts:
      - name: render
        path: /render.yml
  - container:
      env:
      - name: RUNNER_INPUT_PATH
        value: '{{inputs.artifacts.input-parameters.path}}'
      image: gcr.io/projectvoltron/helm-runner:de65286
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: input-parameters
        path: /helm-args
    name: jira-install-install-db-postgres-install-helm-run-helm
    outputs:
      artifacts:
      - globalName: jira-install-install-db-postgres-install-helm-run-helm-release
        name: helm-release
        path: /helm-release
      - globalName: jira-install-install-db-postgres-install-helm-run-additional
        name: additional
        path: /additional

