services:
  dgraph:
    image: dgraph/standalone:latest
    environment:
      DGRAPH_ALPHA_LAMBDA: "url=http://lambda:8686/graphql-worker"
    ports:
      - "8080:8080"
      - "9080:9080"
      - "8000:8000"
    depends_on:
      - lambda
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
  lambda:
    build: ./lambda
    ports:
      - "8686:8686"
    environment:
      DQL_URL: dgraph:9080
      DGRAPHQL_URL: http://dgraph:8080
      DGRAPH_URL: http://dgraph:8080
  populate:
    image: alpine/curl:latest
    entrypoint: sh
    command: ./populate.sh
    working_dir: /mnt
    restart: on-failure
    depends_on:
      - dgraph
    volumes:
      - ./assets:/mnt
