apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}-cluster-policy
  labels:
  {{- include "engine.labels" . | nindent 4 }}
data:
  {{- tpl ((.Files.Glob "cluster-policy.yaml").AsConfig) . | nindent 4 }}
