apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
    {{- include "engine.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "engine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "engine.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.containerRegistry.path }}/{{ .Values.image.name }}:{{ .Values.global.containerRegistry.overrideTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_GRAPH_QL_ADDR
              value: ":8080"
            - name: APP_METRICS_ADDR
              value: "{{ printf ":%s" .Values.controller.metricsPort }}"
            - name: APP_HEALTHZ_ADDR
              value: ":8082"
            - name: APP_LOGGER_DEV_MODE
              value: "true"
            - name: APP_MAX_CONCURRENT_RECONCILES
              value: "1"
            - name: APP_GRAPHQLGATEWAY_USERNAME
              value: "{{ .Values.gateway.username }}"
            - name: APP_GRAPHQLGATEWAY_PASSWORD
              value: "{{ .Values.gateway.password }}"
            - name: APP_MOCKGRAPHQL
              value: "{{ .Values.global.mockGraphQL }}"
            - name: APP_BUILTIN_RUNNER_IMAGE
              value: "{{ .Values.builtInRunnerImage }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
