{{- if .Values.additionalEnvs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret-storage-backend.fullname" . }}
  labels:
    {{- include "secret-storage-backend.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.additionalEnvs | nindent 4 }}
{{- end }}
