ingress-nginx:
  controller:
    ingressClass: capact
    resources:
      requests:
        cpu: 50m
        memory: 150Mi
      limits:
        cpu: 100m
        memory: 300Mi

    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
