apiVersion: v2
name: argo
description: Argo chart for Kubernetes

type: application

version: 0.3.0

dependencies:
  - name: argo
    version: "0.16.7"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.enabled
