apiVersion: v2
name: argo
description: Argo chart for Kubernetes

type: application

version: 0.4.0

dependencies:
  - name: argo
    version: "1.0.0"
    repository: https://argoproj.github.io/argo-helm
    condition: argo.enabled
