apiVersion: v2
name: argo
description: Argo chart for Kubernetes

type: application

version: 0.6.0

dependencies:
  - name: argo-workflows
    version: "0.8.0"
    repository: https://argoproj.github.io/argo-helm
    condition: argo-workflows.enabled
  - name: minio
    version: "7.1.6"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
