ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.database.mongodb
  displayName: MongoDB config
  description: Defines configuration for MongoDB
  documentationURL: https://docs.mongodb.com/manual/
  supportURL: https://www.mongodb.com/
  iconURL: https://webassets.mongodb.com/_com_assets/cms/MongoDB_Logo_FullColorBlack_RGB-4td3yuxzjs.png
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev
  attributes:
    cap.core.attribute.workload.stateful:
      revision: 0.1.0
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for MongoDB configuration",
        "examples": [
          {
            "user": {
              "username": "username",
              "password": "password"
            },
            "rootPassword": "pass",
            "defaultDBName": "default_db",
            "host": "host",
            "port": 27017,
          }
        ],
        "required": [
            "user",
            "defaultDBName",
            "rootPassword",
            "host",
            "port"
        ],
        "$ocfRefs": {
          "hostname": {
            "name": "cap.core.type.networking.hostname",
            "revision": "0.1.0"
          }
          "port": {
            "name": "cap.core.type.networking.port",
            "revision": "0.1.0"
          }
        },
        "properties": {
          "user": {
            "$id": "#/properties/user",
            "type": "object",
            "title": "Defines custom user details",
            "required": [
                "username",
                "password"
            ],
            "properties": {
              "username": {
                "$id": "#/properties/user/properties/username",
                "type": "string",
                "title": "Create the specified custom user.",
                "default": "postgres"
              },
              "password": {
                "$id": "#/properties/user/properties/password",
                "type": "string",
                "title": "Sets the custom user password"
              }
            },
            "additionalProperties": false
          },
          "defaultDBName": {
            "$id": "#/properties/defaultDBName",
            "type": "string",
            "title": "Defines a name for the default database that is created"
          },
          "rootPassword": {
            "$id": "#/properties/rootPassword",
            "type": "string",
            "title": "Defines a root password"
          },
          "host": {
            "$ref": "#/$ocfRefs/hostname"
          },
          "port": {
            "$ref": "#/$ocfRefs/port"
          },
        },
        "additionalProperties": false
      }

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
