ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.database.mongodb
  displayName: MongoDB config
  description: Defines configuration for MongoDB
  documentationURL: https://docs.mongodb.com/manual/
  supportURL: https://www.mongodb.com/
  iconURL: https://webassets.mongodb.com/_com_assets/cms/MongoDB_Logo_FullColorBlack_RGB-4td3yuxzjs.png
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
  attributes:
    cap.core.attribute.workload.stateful:
      revision: 0.1.0
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for MongoDB configuration",
        "examples": [
          {
            "user": {
              "username": "username",
              "password": "password"
            },
            "rootPassword": "pass",
            "defaultDBName": "default_db",
            "replicas": [
              "mongodb-1:27017"
            ],
            "replicaSetName": "rs0"
          }
        ],
        "required": [
          "user",
          "defaultDBName",
          "rootPassword",
          "replicas"
        ],
        "$ocfRefs": {
          "hostname": {
            "name": "cap.core.type.networking.hostname",
            "revision": "0.1.0"
          },
          "port": {
            "name": "cap.core.type.networking.port",
            "revision": "0.1.0"
          }
        },
        "properties": {
          "user": {
            "$id": "#/properties/user",
            "type": "object",
            "title": "Defines custom user details",
            "required": [
              "username",
              "password"
            ],
            "properties": {
              "username": {
                "$id": "#/properties/user/properties/username",
                "type": "string",
                "title": "Create the specified custom user.",
                "default": "postgres"
              },
              "password": {
                "$id": "#/properties/user/properties/password",
                "type": "string",
                "title": "Sets the custom user password"
              }
            },
            "additionalProperties": false
          },
          "defaultDBName": {
            "$id": "#/properties/defaultDBName",
            "type": "string",
            "title": "Defines a name for the default database that is created"
          },
          "rootPassword": {
            "$id": "#/properties/rootPassword",
            "type": "string",
            "title": "Defines a root password"
          },
          "host": {
            "$ref": "#/$ocfRefs/hostname"
          },
          "port": {
            "$ref": "#/$ocfRefs/port"
          },
          "replicas": {
            "$id": "#/properties/replicas",
            "type": "array",
            "title": "List of replica endpoints",
            "items": {
              "type": "string"
            }
          },
          "replicaSetName": {
            "$id": "#/properties/replicaSetName",
            "type": "string",
            "title": "Name of the replica set"
          },
          "replicaSetHostnames": {
            "$id": "#/properties/replicaSetHostnames",
            "type": "boolean",
            "title": "The replicaSetHostnames schema",
            "default": true
          },
          "enableIPv6": {
            "$id": "#/properties/enableIPv6",
            "type": "boolean",
            "title": "The enableIPv6 schema",
            "default": false
          },
          "directoryPerDB": {
            "$id": "#/properties/directoryPerDB",
            "type": "boolean",
            "title": "The directoryPerDB schema",
            "default": false
          },
          "systemLogVerbosity": {
            "$id": "#/properties/systemLogVerbosity",
            "type": "integer",
            "title": "The systemLogVerbosity schema",
            "default": 0
          },
          "disableSystemLog": {
            "$id": "#/properties/disableSystemLog",
            "type": "boolean",
            "title": "The disableSystemLog schema",
            "default": false
          },
          "configuration": {
            "$id": "#/properties/configuration",
            "type": "string",
            "title": "The configuration schema",
            "default": ""
          },
          "initdbScripts": {
            "$id": "#/properties/initdbScripts",
            "type": "object",
            "title": "The initdbScripts schema",
            "default": {},
            "additionalProperties": true
          }
        },
        "additionalProperties": false
      }

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
