# syntax = docker/dockerfile:1-experimental

FROM alpine:latest

WORKDIR /

COPY hack/mock/ /mock/
COPY hack/mock/postgresql-input.yaml /out/
COPY hack/mock/cloudsql-input.yaml /out/
COPY hack/mock/jira-cloud-input.yaml /out/
COPY hack/mock/jira-helm-input.yaml /out/
COPY hack/mock/jira-cloud-values.yaml /out/

COPY hack/mock/produce-helm-cloud-values.sh /
COPY hack/mock/upload-type-instances.sh /

RUN chmod +x /produce-helm-cloud-values.sh
RUN chmod +x /upload-type-instances.sh

RUN apk add yq --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community


LABEL source=git@github.com:Project-Voltron/go-voltron.git
CMD ["sleep", "5"]
