ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.analytics.elasticsearch
  displayName: Elasticsearch instance config
  description: Defines configuration for Elasticsearch instance
  documentationURL: https://www.elastic.co/what-is/elasticsearch
  supportURL: https://github.com/elastic/elasticsearch/issues
  iconURL: https://helm.elastic.co/icons/elasticsearch.png
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for Elasticsearch configuration",
        "required": [
            "version",
            "username",
            "password"
        ],
        "$ocfRefs": {
          "semVer": {
            "name": "cap.core.type.versioning.semver",
            "revision": "0.1.0"
          },
          "hostname": {
            "name": "cap.core.type.networking.hostname",
            "revision": "0.1.0"
          }
        },
        "properties": {
          "version": {
            "$ref": "#/$ocfRefs/semVer"
          },
          "host": {
            "$ref": "#/$ocfRefs/hostname"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }


signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
