# shellcheck shell=bash
# shellcheck disable=SC2034

#
# Dependencies
#

# Upgrade binary versions in a controlled fashion
# along with the script contents (config, flags...)
readonly STABLE_KUBERNETES_VERSION=v1.19.1
readonly STABLE_KIND_VERSION=v0.9.0
readonly STABLE_HELM_VERSION=v3.3.4
readonly STABLE_CONTROLLER_GEN_VERSION=v0.5.0
readonly STABLE_KUBEBUILDER_VERSION=2.3.1
readonly STABLE_GQLGEN_VERSION=v0.13.0

#
# Kubernetes installation
#

readonly VOLTRON_NAMESPACE="voltron-system"
readonly VOLTRON_RELEASE_NAME="voltron"
readonly KIND_DEV_CLUSTER_NAME="kind-dev-voltron"
readonly KIND_CI_CLUSTER_NAME="kind-ci-voltron"

#
# OCF
#

readonly DEFAULT_OCF_VERSION="0.0.1"
readonly CAPACT_OCH_MANIFESTS_SOURCE_REPO_URL="git@github.com:Project-Voltron/go-voltron.git"
readonly CAPACT_OCH_MANIFESTS_SOURCE_REPO_SSHKEY="LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDSTNEQmpXQjhTT1cvS3pjTWwyWm1ZTmtKRXZQcW5QRDY1RGVhQ0lrMDZjZ0FBQUpBVHIyOHJFNjl2Ckt3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ0kzREJqV0I4U09XL0t6Y01sMlptWU5rSkV2UHFuUEQ2NURlYUNJazA2Y2cKQUFBRURJTk51VHg3dG1oUVY1dFFxRFVpbDVxOTZwWFE2ak5TdnR2bEVBRmowWUNJamNNR05ZSHhJNWI4ck53eVhabVpnMgpRa1M4K3FjOFBya041b0lpVFRweUFBQUFESE5zYlVCemJHMHRaR1ZzYkFFPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K"
readonly CAPACT_OCH_MANIFESTS_SOURCE_REPO_REF="master"

#
# Infra
#

readonly JSON_GO_GEN_IMAGE_VERSION="0.1.1"
readonly GRAPHQL_SCHEMA_LINTER_IMAGE_VERSION="0.1.0"

#
# Development
#

readonly VOLTRON_ENABLE_POPULATOR="true"
readonly VOLTRON_USE_TEST_SETUP="false"

#
# Cluster Configuration
#

readonly VOLTRON_INCREASE_RESOURCE_LIMITS="true"
