{
 "title": "Capact / Engine/ Controller",
 "tags": [ "capact" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go memstats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"capact-system\",pod=~\"capact-engine-.*\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"capact-system\", pod=~\"capact-engine-.*\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"capact-system\",pod=~\"capact-engine-.*\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"capact-system\",pod=~\"capact-engine-.*\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "description": "Resident: The amount of memory the process is using from the kernel.\n\nVirtual: The amount of address space that a process is managing. This includes all types of memory, both in RAM and swapped out.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"capact-system\",pod=~\"capact-engine-.*\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"capact-system\",pod=~\"capact-engine-.*\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{namespace=\"capact-system\", pod=~\"capact-engine-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"capact-system\", pod=~\"capact-engine-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "description": "The key insight is that this metric is the pause time, and since Go version 1.6 pause times have been a few hundred microseconds max, which won't impact you unless you have seriously low latency requirements.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"capact-system\", pod=~\"capact-engine-.*\"}",
     "legendFormat": "{{pod}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"capact-system\", pod=~\"capact-engine-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Runtime Metrics - K8s Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Average Reconcile Latency",
   "type": "graph",
   "description": "The average time to describe how long in seconds an item stays in workqueue during the last 1minute before being precessed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s", "label": "Average reconcile time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{service=\"capact-engine-controller\", name=\"action\"}[1m]) / rate(workqueue_queue_duration_seconds_count{service=\"capact-engine-controller\", name=\"action\"}[1m])",
     "legendFormat": "Action"
    }
   ]
  },
  {
   "title": "Average Reconcile Time",
   "type": "graph",
   "description": "This chart shows how long it took for the controller to process a custom resource.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s", "label": "Average reconcile time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_work_duration_seconds_sum{service=\"capact-engine-controller\", name=\"action\"}[1m]) / rate(workqueue_work_duration_seconds_count{service=\"capact-engine-controller\", name=\"action\"}[1m])",
     "legendFormat": "Action"
    }
   ]
  },
  {
   "title": "Queue work item durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{service=\"capact-engine-controller\", name=\"action\"}",
     "legendFormat": "The longest unfinished work [sec]"
    },
    {
     "expr": "workqueue_longest_running_processor_seconds{service=\"capact-engine-controller\", name=\"action\"}",
     "legendFormat": "The longest runnig [sec]"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "description": "This chart shows how many custom resources are waiting for processing by the controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{service=\"capact-engine-controller\", name=\"action\"}",
     "legendFormat": "Action"
    }
   ]
  },
  {
   "title": "Average number of new items added to queue during 1 minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{service=\"capact-engine-controller\", name=\"action\"}[1m])",
     "legendFormat": "Action"
    }
   ]
  },
  {
   "title": "Average number of retries handled by workqueue during 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{service=\"capact-engine-controller\", name=\"action\"}[5m])",
     "legendFormat": "Action"
    }
   ]
  }
 ]
}