env:
  node: true
  es2020: true
extends:
  - airbnb-base

parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.ts', '.js']

rules:
  import/extensions: ['off']
  max-len: [1, 120]
