# Default values for voltron.
global:
  containerRegistry:
    path: gcr.io/projectvoltron
    # Overrides the image tag for all Voltron component. Default is the sub-chart appVersion.
    overrideTag: "latest"
  domainName: "dev.cluster.projectvoltron.dev"
  mockEngineGraphQL: "false"

  database:
    endpoint: bolt://neo4j-neo4j.neo4j:7687
    username: neo4j
    password: okon

  gateway:
    auth:
      username: graphql
      password: t0p_s3cr3t

integrationTest:
  image:
    name: e2e-test
    pullPolicy: IfNotPresent
  expectedNumberOfRunningPods: 21
