ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.productivity.jira # Computed during fetching the manifest
  name: install
  displayName: "Install"
  description: "Install action for Jira"
  documentationURL: https://support.atlassian.com/jira-software-cloud/resources/
  supportURL: https://www.atlassian.com/software/jira
  iconURL: https://www.atlassian.com/pl/dam/jcr:e33efd9e-e0b8-4d61-a24d-68a48ef99ed5/Jira%20Software@2x-blue.png
  maintainers:
    - email: team-dev@projectvoltron.dev
      name: Voltron Dev Team
      url: https://projectvoltron.dev

spec:
  input:
    parameters:
      jsonSchema:
        value: |-
          {
            "$schema": "http://json-schema.org/draft-07/schema",
            "$ocfRefs": {
              "inputType": {
                "name": "cap.type.productivity.jira.install-input",
                "revision": "0.1.0"
              }
            },
            "allOf": [ { "$ref": "#/$ocfRefs/inputType" } ]
          }
  output:
    typeInstances:
      jira-config:
        typeRef:
          path: cap.type.productivity.jira.config
          revision: 0.1.0

signature:
  och: eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9
