# Copyright 2022 Nordcloud Oy or its affiliates. All Rights Reserved.

trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - 'v*'
pr:
  branches:
    include:
    - 'master'

pool:  
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: nordcloud-templates
      type: github
      name: nordcloud/azure-pipelines-templates
      endpoint: nordcloud
      
variables:
  NODE_VERSION: '12'
  GOPATH: '$(Pipeline.Workspace)/gopath'
  GO_VERSION: '1.16'
  GOPROXY: 'direct'
  GOSUMDB: 'off'
  USER: 'root'

stages:
  # - stage: 'Test'
  #   jobs:
  #   - job: 'TestJob'
  #     container: eu.gcr.io/rnd-docker-public/ultimate-toolkit:3
  #     steps:
  #       - template: 'templates/test.yml'
  #   displayName: 'Run tests'

  - stage: 'Build'
    dependsOn:
    # - 'Test'
    # condition: "succeeded('Test')"
    jobs:
    - job: 'BuildJob'
      # container: eu.gcr.io/rnd-docker-public/ultimate-toolkit:3
      steps:
        - template: 'templates/build.yml'
    displayName: 'Run build app images'