name: periodic-cluster-integration-tests
on:
  schedule:
  - cron: '0 */2 * * *'

jobs:
  integration-tests:
    name: Cluster integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GKE_CREDS }}
      - name: Get cluster credentials
        run: |
          gcloud config set project ${PROJECT_ID}
          gcloud container clusters get-credentials ${TF_VAR_cluster_name} --zone=${TF_VAR_region}
      - name: Network enable
        id: network-enable
        run: |
          ./hack/ci/add-job-ip.sh
      - name: Test Voltron release
        run: |
          helm test voltron --namespace=voltron-system --timeout="10m" --logs
      - name: Network cleanup
        # The `always()` is needed to always run the step, even if previous ones failed. From docs: "If your if expression does not contain any of the status functions it will automatically result with success()."
        # Without that it will results in: `Evaluating: (success() && (steps.network-enable.outcome == 'success'))`
        # source: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
        if: ${{ always() && steps.network-enable.outcome == 'success' }}
        env:
          IP_ADDED_JOB: "${{ steps.network-enable.outputs.JOB_IP }}"
        run: |
          ./hack/ci/remove-job-ip.sh

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [ integration-tests ]
    if: always()

    steps:
      - name: Slack Notification
        if: ${{ always() && needs.integration-tests.result != 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Voltron CI Notifier
          SLACK_COLOR: 'red'
          SLACK_TITLE: 'Message'
          SLACK_CHANNEL: 'capact-dev-private'
          SLACK_MESSAGE: 'Periodic tests failed :ahhhhhhhhh:'
          SLACK_ICON_EMOJI: ':this-is-fine:'
          SLACK_FOOTER: "Hopefully it is not an error, it's gorgeous feature"
          SLACK_WEBHOOK: ${{ secrets.SLACK_PRIV_DEV_TEAM_WEBHOOK }}
