name: Remote Repository Sync

on:
  schedule:
  - cron: '0 1 * * *' # At 01:00 every day
  workflow_dispatch:
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:capactio/capact.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:structsure/capact.git"
          destination_branch: "refs/heads/*"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
