on:
  push:
    branches:
      - master
  schedule:
  - cron: '13 */12 * * *'
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:Project-Voltron/go-voltron.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:structsure/go-voltron.git"
          destination_branch: "refs/heads/*"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
