name: Build-Images

on: 
  push:
    paths:
    - '**.go'
    - '**.graphql'
    - '**.yaml'
    branches:    
    - 'devops-20201014'

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_CREDS }}
          project_id: projectvoltron
          export_default_credentials: true

      # - name: pull & push
      #   run: |
      #     docker pull gcr.io/projectvoltron/och:latest
      #     docker tag  gcr.io/projectvoltron/och:latest gcr.io/projectvoltron/och:test3
      #     docker image ls
      #     gcloud auth configure-docker -q
      #     docker push gcr.io/projectvoltron/och:test3         
      #     exit 1


      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{secrets.GO_VERSION}}

      - name: Run linting
        run: | 
          make test-lint
        env:
          SKIP_DEPS_INSTALLATION: false

      - name: Run unit tests
        run: make test-unit

      - name: build image
        run: |
          export DOCKER_TAG=$(echo ${GITHUB_SHA:0:7})
          make build-all-images

      - name: push image
        run: |
          export DOCKER_TAG=$(echo ${GITHUB_SHA:0:7})
          gcloud auth configure-docker -q
          make push-all-images
          echo "finished"
