name: Build-Images

on: 
  push:
    paths:
    - '**.go'
    - '**.graphql'
    - '**.yaml'
    branches:    
    - 'devops-20201014'

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest


      
    steps:    
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCR_CREDS }}

      - name: Setup env
        run: |
          . ./env_setup.sh


      # - name: Setup golang
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: ${{env.GO_VERSION}}

      # - name: Run linting
      #   run: | 
      #     make test-lint
      #   env:
      #     SKIP_DEPS_INSTALLATION: false

      # - name: Run unit tests
      #   run: make test-unit

      # - name: Run generation
      #   run: make gen-go-api
        
      - name: Build & push image
        run: |
          for APP in ${APPS}
          do  
            echo ${APP}
            sleep 1
            date
            echo ""
          done

          


      # - name: push image
      #   run: |
      #     gcloud auth configure-docker --project ${PROJECT_ID} -q
      #     make push-all-images


