name: Build-Images

on: 
  push:
    paths:
    - '**.go'
    - '**.graphql'
    - '**.yaml'
    branches:    
    - 'devops-20201014'

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      # - name: Environment setup
      #   run: |
      #     pwd
      #     ls -la
      #     echo ${GO-VERSION}
      #     . ./env_setup.sh
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${GO-VERSION}

      - name: Run linting
        run: | 
          go mod download
          make test-lint
        env:
          SKIP_DEPS_INSTALLATION: false
          # RUN_ON_CI: true
          # GO111MODULE: on
          # GOPATH: /home/runner/go

      - name: Run unit tests
        run: make test-unit

      - name: build image
        run: |
          export DOCKER_TAG=$(echo ${GITHUB_SHA:0:7})
          make build-all-images
        #env:
          #DEFAULT_BRANCH: devops-20201014
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
