name: Master build

on: 
  push:
    paths:
    - '**.yaml'
    branches: 
    - 'devops-*'


jobs:
  entry-tests:
    name: Git crypt tests
    runs-on: ubuntu-latest
      
    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup env
        run: |
          . ./env_setup.sh
          sudo apt-get update -y && sudo apt-get install -y git-crypt
          echo ${{ secrets.KEY }}
          echo "12345678" |gpg --batch --yes --passphrase-fd 0 local.key.asc| git-crypt unlock - 
          cat data/qqq.txt
