name: Master build

on: 
  push:
    paths:
    - '**.txt'
    branches: 
    - 'devops-*'


jobs:
  entry-tests:
    name: Git crypt tests
    runs-on: ubuntu-latest
      
    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup env
        run: |
          . ./env_setup.sh
          gpg --decrypt local.key.asc < ${{ secrets.KEY}}| git-crypt unlock - 
          cat data/qqq.txt
